spring:
  application:
    name: hire-genie

# AI-Configurations:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_APIKEY}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.7

# DB-Configurations:
  datasource:
    url: jdbc:postgresql://localhost:5421/hire_genie_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

# JPA/Hibernate Configurations:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
